// Builds Pehchaan's brand assets from the font files, so the seal never depends on
// font loading and the app icons match the in-app seal exactly.
//
//   1. Extracts the Devanagari letter "प" (Anek Devanagari 700) as SVG path data
//      into src/design/glyphs.ts, centred in a 100x100 box.
//   2. Renders the seal onto the PWA icons (192, 512, 512 maskable, 180 apple-touch)
//      and writes public/favicon.svg.
//
// Run with: npm run brand
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import opentype from "opentype.js";
import sharp from "sharp";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const fontPath = join(
  root,
  "node_modules/@fontsource/anek-devanagari/files/anek-devanagari-devanagari-700-normal.woff",
);
const buf = readFileSync(fontPath);
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));

// Look the glyph up through the cmap directly (U+092A), skipping text shaping:
// a single isolated consonant needs none, and shaping mangles some coordinates.
const glyphIndex = font.tables.cmap.glyphIndexMap[0x092a];
if (!glyphIndex) throw new Error("U+092A not found in the font");
const pa = font.glyphs.get(glyphIndex);

// Lay the glyph out at 1000 units, then fit it into a 100x100 box, centred.
const bb = pa.getPath(0, 0, 1000).getBoundingBox();
const w = bb.x2 - bb.x1;
const h = bb.y2 - bb.y1;
const target = 50;
const scale = target / Math.max(w, h);
const ox = 50 - (w * scale) / 2 - bb.x1 * scale;
// Optical centring: Devanagari letters hang from the headline, so nudge down slightly.
const oy = 50 - (h * scale) / 2 - bb.y1 * scale + 1;
// Serialise the commands ourselves: opentype.js 2's toPathData "optimize" pass emits NaN.
const n = (v) => {
  if (!Number.isFinite(v)) throw new Error("Glyph path has a non-finite coordinate");
  return String(Math.round(v * 100) / 100);
};
const d = pa
  .getPath(ox, oy, 1000 * scale)
  .commands.map((c) => {
    switch (c.type) {
      case "M":
      case "L":
        return `${c.type}${n(c.x)} ${n(c.y)}`;
      case "Q":
        return `Q${n(c.x1)} ${n(c.y1)} ${n(c.x)} ${n(c.y)}`;
      case "C":
        return `C${n(c.x1)} ${n(c.y1)} ${n(c.x2)} ${n(c.y2)} ${n(c.x)} ${n(c.y)}`;
      case "Z":
        return "Z";
      default:
        throw new Error("Unknown path command " + c.type);
    }
  })
  .join("");

mkdirSync(join(root, "src/design"), { recursive: true });
writeFileSync(
  join(root, "src/design/glyphs.ts"),
  `// Generated by scripts/build-brand.mjs from Anek Devanagari 700. Do not edit by hand.
// The letter "प" (pa), the first letter of पहचान, centred in a 100x100 box.
export const PA_GLYPH_PATH =
  "${d}";
`,
);
console.log("src/design/glyphs.ts");

// The seal geometry mirrors src/components/Seal.tsx (viewBox 0 0 100 100).
function sealSvg({ size, bg, ring, inner, letter, pad = 0, rounded = false }) {
  const inset = pad; // fraction of the canvas left around the seal (maskable safe zone)
  const s = 100 / (1 - inset * 2);
  const o = -(s - 100) / 2;
  const radius = rounded ? s * 0.22 : 0;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="${o} ${o} ${s} ${s}">
  <rect x="${o}" y="${o}" width="${s}" height="${s}" rx="${radius}" fill="${bg}"/>
  <circle cx="50" cy="50" r="46" fill="none" stroke="${ring}" stroke-width="3.2"/>
  <circle cx="50" cy="50" r="38.5" fill="none" stroke="${inner}" stroke-width="1.6" stroke-dasharray="4 3"/>
  <path d="${d}" fill="${letter}"/>
</svg>`;
}

const iconDir = join(root, "public/icons");
mkdirSync(iconDir, { recursive: true });

const dark = { bg: "#0A0E1F", ring: "#D9B874", inner: "#8C95FF", letter: "#B3B9FF" };
const brand = { bg: "#3A45D6", ring: "#E9CF96", inner: "#C9CDFF", letter: "#FFFFFF" };

const jobs = [
  ["icon-192.png", sealSvg({ size: 192, ...dark, pad: 0.1 })],
  ["icon-512.png", sealSvg({ size: 512, ...dark, pad: 0.1 })],
  // Maskable: keep the seal inside the 80% safe zone.
  ["icon-512-maskable.png", sealSvg({ size: 512, ...brand, pad: 0.2 })],
  ["apple-touch-icon.png", sealSvg({ size: 180, ...dark, pad: 0.12 })],
];
for (const [name, svg] of jobs) {
  await sharp(Buffer.from(svg)).png({ compressionLevel: 9 }).toFile(join(iconDir, name));
  console.log("public/icons/" + name);
}

writeFileSync(join(root, "public/favicon.svg"), sealSvg({ size: 64, ...dark, pad: 0.04, rounded: true }));
console.log("public/favicon.svg");
