-- Initial schema (spec 15.2). Generated by drizzle-kit from src/store/schema.ts; foreign keys are left
-- unqualified so the tables live in whichever schema the relay uses (PG_SCHEMA, D-018).
CREATE TABLE "audit_events" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"at" timestamp with time zone DEFAULT now() NOT NULL,
	"kind" text NOT NULL,
	"subject" text,
	"meta" jsonb DEFAULT '{}'::jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "contact_bindings" (
	"target_device_id" text NOT NULL,
	"sender_device_id" text NOT NULL,
	"via_grant_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone,
	CONSTRAINT "contact_bindings_target_device_id_sender_device_id_pk" PRIMARY KEY("target_device_id","sender_device_id")
);
--> statement-breakpoint
CREATE TABLE "contact_grants" (
	"target_device_id" text NOT NULL,
	"grant_id" text NOT NULL,
	"secret_hash" "bytea" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone,
	CONSTRAINT "contact_grants_target_device_id_grant_id_pk" PRIMARY KEY("target_device_id","grant_id"),
	CONSTRAINT "contact_grants_secret_hash_len" CHECK (length("contact_grants"."secret_hash") = 32)
);
--> statement-breakpoint
CREATE TABLE "devices" (
	"device_id" text PRIMARY KEY NOT NULL,
	"device_pub" "bytea" NOT NULL,
	"platform" text,
	"app_version" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_on" date DEFAULT current_date NOT NULL,
	"retired_at" timestamp with time zone,
	"blocked_at" timestamp with time zone,
	"block_reason" text,
	CONSTRAINT "devices_device_pub_len" CHECK (length("devices"."device_pub") = 65)
);
--> statement-breakpoint
CREATE TABLE "lab_attacks" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"at" timestamp with time zone DEFAULT now() NOT NULL,
	"attack" text NOT NULL,
	"asker" text NOT NULL,
	"answerer" text NOT NULL,
	"verdict" text,
	"invalid_reason" text,
	"failed_checks" smallint[],
	"false_green" boolean DEFAULT false NOT NULL,
	CONSTRAINT "lab_attacks_attack" CHECK ("lab_attacks"."attack" in ('change','replay','forge'))
);
--> statement-breakpoint
CREATE TABLE "push_subscriptions" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"device_id" text NOT NULL,
	"endpoint" text NOT NULL,
	"p256dh" text NOT NULL,
	"auth" text NOT NULL,
	"vapid_key_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_success_at" timestamp with time zone,
	"failure_count" integer DEFAULT 0 NOT NULL,
	"expired_at" timestamp with time zone,
	CONSTRAINT "push_subscriptions_endpoint_unique" UNIQUE("endpoint")
);
--> statement-breakpoint
ALTER TABLE "contact_bindings" ADD CONSTRAINT "contact_bindings_target_device_id_devices_device_id_fk" FOREIGN KEY ("target_device_id") REFERENCES "devices"("device_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contact_bindings" ADD CONSTRAINT "contact_bindings_sender_device_id_devices_device_id_fk" FOREIGN KEY ("sender_device_id") REFERENCES "devices"("device_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contact_grants" ADD CONSTRAINT "contact_grants_target_device_id_devices_device_id_fk" FOREIGN KEY ("target_device_id") REFERENCES "devices"("device_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "push_subscriptions" ADD CONSTRAINT "push_subscriptions_device_id_devices_device_id_fk" FOREIGN KEY ("device_id") REFERENCES "devices"("device_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_events_at" ON "audit_events" USING btree ("at");--> statement-breakpoint
CREATE INDEX "contact_bindings_sender" ON "contact_bindings" USING btree ("sender_device_id");--> statement-breakpoint
CREATE INDEX "push_subs_active" ON "push_subscriptions" USING btree ("device_id") WHERE expired_at is null;